"""Built-in SFX presets matching the game's existing sound effects.

These mirror the 15 SFX definitions from the C64 game engine's sound_auditor.asm.
"""

from sid_sfx.schema import SfxPatch, Waveform


PRESETS = {
    "fire": SfxPatch(
        name="fire",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x8F, freq_lo=0x5C,
        attack=8, decay=3, sustain=8, release=4,
        pw_hi=0x39, duration_frames=15,
        sweep_target_hi=0x0E, sweep_target_lo=0x21,
        sweep_frames=13, sweep_type="exponential",
        filter_cutoff=0x2F, filter_resonance=0x5, filter_mode="lowpass",
        description="Triangle sweep laser pew — 2155Hz to 212Hz",
    ),
    "explode": SfxPatch(
        name="explode",
        voice=2, waveform=Waveform.NOISE,
        freq_hi=0x08, freq_lo=0x00,
        attack=0, decay=9, sustain=0, release=9,
        pw_hi=0x00, duration_frames=15,
        description="Noise burst explosion — mid-frequency noise with slow decay",
    ),
    "hit": SfxPatch(
        name="hit",
        voice=2, waveform=Waveform.NOISE,
        freq_hi=0x5C, freq_lo=0x34,
        attack=0, decay=3, sustain=6, release=9,
        pw_hi=0x96, duration_frames=8,
        sweep_target_hi=0x2D, sweep_target_lo=0x9A,
        sweep_frames=5, sweep_type="exponential",
        filter_cutoff=0x90, filter_resonance=0xF, filter_mode="lowpass",
        description="Noise sweep hit — 1386Hz to 686Hz, lowpass max resonance",
    ),
    "weakpoint_hit": SfxPatch(
        name="weakpoint_hit",
        voice=1, waveform=Waveform.PULSE,
        freq_hi=0x09, freq_lo=0x00,
        attack=0, decay=7, sustain=2, release=7,
        pw_hi=0x05, duration_frames=12,
        description="Deeper metallic pulse — weakpoint damage with sustain",
    ),
    "enemy_hit": SfxPatch(
        name="enemy_hit",
        voice=1, waveform=Waveform.NOISE,
        freq_hi=0x21, freq_lo=0x61,
        attack=6, decay=9, sustain=0, release=0,
        pw_hi=0x2A, duration_frames=38,
        sweep_target_hi=0xF0, sweep_target_lo=0x77,
        sweep_frames=27, sweep_type="exponential",
        filter_cutoff=0x0A, filter_resonance=0x6, filter_mode="lowpass",
        vibrato_rate=31.0, vibrato_depth=200,
        description="NOISE @ 502Hz sweep to 3615Hz — enemy takes damage",
    ),
    "march": SfxPatch(
        name="march",
        voice=3, waveform=Waveform.PULSE,
        freq_hi=0x21, freq_lo=0x00,
        attack=15, decay=4, sustain=5, release=4,
        pw_hi=0xC8, duration_frames=10,
        sweep_target_hi=0x18, sweep_target_lo=0x3C,
        sweep_frames=10, sweep_type="exponential",
        filter_cutoff=0x24, filter_resonance=0xE, filter_mode="bandpass",
        vibrato_rate=33.0, vibrato_depth=252,
        description="Pulse sweep march — bandpass filtered with vibrato",
    ),
    "kraft_alarm": SfxPatch(
        name="kraft_alarm",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x04, freq_lo=0x00,
        attack=0, decay=2, sustain=0, release=8,
        pw_hi=0x00, duration_frames=10,
        description="Rising triangle alarm tone",
    ),
    "game_over": SfxPatch(
        name="game_over",
        voice=1, waveform=Waveform.PULSE,
        freq_hi=0x18, freq_lo=0x00,
        attack=2, decay=2, sustain=10, release=8,
        pw_hi=0x08, duration_frames=45,
        description="Descending pulse tone with long sustain — game over",
    ),
    "death": SfxPatch(
        name="death",
        voice=2, waveform=Waveform.NOISE,
        freq_hi=0x14, freq_lo=0x00,
        attack=0, decay=10, sustain=0, release=12,
        pw_hi=0x00, duration_frames=20,
        description="Noise crash with long decay — player death",
    ),
    "warp": SfxPatch(
        name="warp",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x04, freq_lo=0x00,
        attack=2, decay=8, sustain=8, release=8,
        pw_hi=0x00, duration_frames=60,
        description="Slow rising triangle sweep — warp effect",
    ),
    "portal_ping": SfxPatch(
        name="portal_ping",
        voice=1, waveform=Waveform.TRIANGLE,
        freq_hi=0x20, freq_lo=0x00,
        attack=0, decay=2, sustain=0, release=0,
        pw_hi=0x00, duration_frames=5,
        description="Very brief high triangle blip — portal ping",
    ),
    "powerup": SfxPatch(
        name="powerup",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x1C, freq_lo=0xD6,
        attack=0, decay=8, sustain=10, release=0,
        pw_hi=0x00, duration_frames=15,
        description="Rising triangle arpeggio — powerup collect",
    ),
    "bounce": SfxPatch(
        name="bounce",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x30, freq_lo=0x00,
        attack=0, decay=0, sustain=0, release=0,
        pw_hi=0x00, duration_frames=3,
        description="Ultra-short high sawtooth blip — bounce",
    ),
    "blaster_bolt": SfxPatch(
        name="blaster_bolt",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x28, freq_lo=0x00,
        attack=0, decay=6, sustain=0, release=4,
        pw_hi=0x00, duration_frames=8,
        sweep_target_hi=0x03, sweep_target_lo=0x00,
        sweep_type="exponential",
        description="Descending sawtooth sweep — blaster bolt 'pew'",
    ),
    # --- Blaster variations (weighted random cycling in engine) ---
    # Weight 3/8: most common shot
    "xwing_blaster": SfxPatch(
        name="xwing_blaster",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x80, freq_lo=0x00,
        attack=0, decay=4, sustain=0, release=3,
        pw_hi=0x00, duration_frames=6,
        sweep_target_hi=0x09, sweep_target_lo=0xFB,
        sweep_type="exponential",
        description="Quick bright blaster pew — X-wing style (weight 3/8)",
    ),
    # Weight 2/8: frequent mid-range punch
    "heavy_repeater": SfxPatch(
        name="heavy_repeater",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x53, freq_lo=0x26,
        attack=0, decay=5, sustain=0, release=4,
        pw_hi=0x00, duration_frames=10,
        sweep_target_hi=0x04, sweep_target_lo=0xFD,
        sweep_type="exponential",
        description="Mid-range sawtooth sweep — heavy repeater (weight 2/8)",
    ),
    # Weight 1/8: occasional heavy hit
    "turbolaser": SfxPatch(
        name="turbolaser",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x42, freq_lo=0x85,
        attack=0, decay=7, sustain=0, release=6,
        pw_hi=0x00, duration_frames=18,
        sweep_target_hi=0x02, sweep_target_lo=0xA9,
        sweep_type="exponential",
        description="Heavy sawtooth sweep — turbolaser blast (weight 1/8)",
    ),
    # Weight 1/8: occasional sharp crack
    "tie_cannon": SfxPatch(
        name="tie_cannon",
        voice=1, waveform=Waveform.PULSE,
        freq_hi=0x80, freq_lo=0x00,
        attack=0, decay=3, sustain=0, release=2,
        pw_hi=0x26, duration_frames=5,
        sweep_target_hi=0x1A, sweep_target_lo=0x9C,
        sweep_type="exponential",
        description="Thin high pulse sweep — TIE cannon crack (weight 1/8)",
    ),
    # --- Shield effects ---
    "shield_on_v3": SfxPatch(
        name="shield_on_v3",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x27, freq_lo=0xE9,
        attack=6, decay=8, sustain=10, release=8,
        pw_hi=0x00, duration_frames=60,
        vibrato_rate=15.0, vibrato_depth=100,
        description="600Hz triangle with 15Hz vibrato — Star Trek force field wobble",
    ),
    # Weight 1/8: rare deep boom
    "ion_cannon": SfxPatch(
        name="ion_cannon",
        voice=1, waveform=Waveform.PULSE,
        freq_hi=0x31, freq_lo=0xE4,
        attack=0, decay=8, sustain=0, release=7,
        pw_hi=0x14, duration_frames=20,
        sweep_target_hi=0x01, sweep_target_lo=0xFF,
        sweep_type="exponential",
        description="Deep narrow-pulse sweep — ion cannon boom (weight 1/8)",
    ),
    "powerup_spread": SfxPatch(
        name="powerup_spread",
        voice=3, waveform=Waveform.PULSE,
        freq_hi=0x35, freq_lo=0x37,
        attack=0, decay=6, sustain=12, release=4,
        pw_hi=0x10, duration_frames=30,
        sweep_target_hi=0x6A, sweep_target_lo=0x6D,
        sweep_frames=30, sweep_type="exponential",
        vibrato_rate=8.0, vibrato_depth=60,
        description="Shimmering pulse sweep — spread powerup collect",
    ),
    "powerup_shield": SfxPatch(
        name="powerup_shield",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x13, freq_lo=0xF5,
        attack=4, decay=8, sustain=13, release=6,
        pw_hi=0x00, duration_frames=45,
        sweep_target_hi=0x10, sweep_target_lo=0xA1,
        sweep_frames=40, sweep_type="linear",
        vibrato_rate=4.0, vibrato_depth=80,
        description="Deep resonant hum — shield powerup collect",
    ),
    "combo": SfxPatch(
        name="combo",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x10, freq_lo=0x00,
        attack=0, decay=9, sustain=0, release=0,
        pw_hi=0x00, duration_frames=10,
        description="Kill combo sting — sawtooth blip",
    ),
    "powerup_speed": SfxPatch(
        name="powerup_speed",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x1A, freq_lo=0x9B,
        attack=7, decay=5, sustain=10, release=3,
        pw_hi=0x75, duration_frames=25,
        sweep_target_hi=0x86, sweep_target_lo=0x59,
        sweep_frames=17, sweep_type="exponential",
        filter_cutoff=0x4E, filter_resonance=0x5, filter_mode="lowpass",
        vibrato_rate=17.0, vibrato_depth=54,
        loop=True,
        description="Rising triangle sweep — speed powerup collect",
    ),
}
